server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangshun1996/cloud2020.git
          search-paths:
            - cloud2020
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

